export const authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
}
export const registrationConstant={
    REGISTER_REQUEST:'REGISTER_REQUEST',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILURE:'REGISTER_FAILURE',
}

export const categoryConstant={
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
    EDIT_CATEGORIES_REQUEST:'EDIT_CATEGORIES_REQUEST',
    EDIT_CATEGORIES_SUCCESS:'EDIT_CATEGORIES_SUCCESS',
    EDIT_CATEGORIES_FAILURE:'EDIT_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST:'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS:'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE:'DELETE_CATEGORIES_FAILURE',
}

export const initialDataConstant={
    GET_ALL_INITIALDATA_REQUEST:'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS:'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE:'GET_ALL_INITIALDATA_FAILURE'
}

export const productsContants={
    GET_ALL_PRODUCTS_REQUEST:'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_FAILURE:'GET_ALL_PRODUCTS_FAILURE',
    GET_ALL_PRODUCTS_SUCCESS:'GET_ALL_PRODUCTS_SUCCESS'
}

export const pageConstants={
    ADD_NEW_PAGE_REQUEST:'ADD_NEW_PAGE_REQUEST',
    ADD_NEW_PAGE_SUCCESS:'ADD_NEW_PAGE_SUCCESS',
    ADD_NEW_PAGE_FAILURE:'ADD_NEW_PAGE_FAILURE',
}