export const authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST'
}
export const registrationConstant={
    REGISTER_REQUEST:'REGISTER_REQUEST',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILURE:'REGISTER_FAILURE',

}